### ISSUE TITLE
make 20th stable release

### ISSUE THREAD

**Issue by tsahara** [iij/mruby#154]
- [x]  mruby#2940 - not applicable
- [x]  mruby#2941 - documentation
- [x]  mruby#2942 - not applicable
- [x]  mruby#2943 - feature change
- [x]  mruby#2944 - question
- [x]  mruby#2945 - change request
- [x]  mruby#2946 - feature change
- [x]  mruby#2947 - spec change
- [x]  mruby#2948 - change request
- [x]  mruby#2949 - spec change
- [x]  mruby#2950 - change request
- [x]  mruby#2951 - feature change
- [x] https://github.com/mruby/mruby/commit/74696ffd9625e4dca43aa010d71020f10030de24 - feature change
- [x] https://github.com/mruby/mruby/commit/3a462fe4687fa2a52d2c9c20d10ae46901292b99 - feature change
- [x]  mruby#2952 - not applicable
- [x]  mruby#2953 - spec change
- [x]  mruby#2954 - not a bug
- [x]  mruby#2955 - not a bug
- [x]  mruby#2956 - feature change
- [x]  mruby#2957 - style change
- [x]  mruby#2958 - style change
- [x]  mruby#2959 - documentation
- [x]  mruby#2960 - refactoring
- [x]  mruby#2961 - spec change
- [x]  mruby#2962 - not a bug
- [x]  mruby#2963 - not applicable
- [x]  mruby#2964 - not applicable
- [x]  mruby#2965 - not applicable
- [x]  mruby#2966 - documentation
- [x]  mruby#2967 - not applicable
- [x]  mruby#2968 - feature change
- [x]  mruby#2969 - not a bug
- [x]  mruby#2970 - feature change
- [x]  mruby#2971 - not applicable
- [x]  mruby#2972 - change request
- [x]  mruby#2973 - not applicable

**Comment by tsahara** [comment]
There are no changes applicable to stable_1_0.
