### ISSUE TITLE
make December 2015 Stable Release

### ISSUE THREAD

**Issue by tsahara** [iij/mruby#155]
- [x] https://github.com/mruby/mruby/issues/2974
- [x] https://github.com/mruby/mruby/issues/2975
- [x] https://github.com/mruby/mruby/issues/2976
- [x] https://github.com/mruby/mruby/issues/2977
- [x] https://github.com/mruby/mruby/issues/2978
- [x] https://github.com/mruby/mruby/issues/2979
- [x] https://github.com/mruby/mruby/issues/2980
- [x] https://github.com/mruby/mruby/issues/2981
- [x] https://github.com/mruby/mruby/issues/2982
- [x] https://github.com/mruby/mruby/issues/2983
- [x] https://github.com/mruby/mruby/issues/2984
- [x] https://github.com/mruby/mruby/issues/2985
- [x] https://github.com/mruby/mruby/issues/2986
- [x] https://github.com/mruby/mruby/issues/2987
- [x] https://github.com/mruby/mruby/issues/2988
- [x] https://github.com/mruby/mruby/issues/2989
- [x] https://github.com/mruby/mruby/issues/2990
- [x] https://github.com/mruby/mruby/issues/2991
- [x] https://github.com/mruby/mruby/issues/2992
- [x] https://github.com/mruby/mruby/issues/2993
- [x] https://github.com/mruby/mruby/issues/2994
- [x] https://github.com/mruby/mruby/issues/2995
- [x] https://github.com/mruby/mruby/issues/2996 - merged https://github.com/iij/mruby/commit/9bb552fdb0223f37256dc4c3f5760578d6a9f618
- [x] https://github.com/mruby/mruby/issues/2997
- [x] https://github.com/mruby/mruby/issues/2998
- [x] https://github.com/mruby/mruby/issues/2999
- [x] https://github.com/mruby/mruby/issues/3000 - merged 356565a9b3de149495b3b6fbe035d50a60d1ae29
- [x] https://github.com/mruby/mruby/issues/3001
- [x] https://github.com/mruby/mruby/issues/3002
- [x] https://github.com/mruby/mruby/issues/3003 - merged https://github.com/iij/mruby/commit/3ccea6c9b653cd58dc6f48d2b2edb70568ee69b4
- [x] https://github.com/mruby/mruby/issues/3004
- [x] https://github.com/mruby/mruby/issues/3005
- [x] https://github.com/mruby/mruby/issues/3006
- [x] https://github.com/mruby/mruby/issues/3007
- [x] https://github.com/mruby/mruby/issues/3008
- [x] https://github.com/mruby/mruby/issues/3009
- [x] https://github.com/mruby/mruby/issues/3010
- [x] https://github.com/mruby/mruby/issues/3011
- [x] https://github.com/mruby/mruby/issues/3012
- [x] https://github.com/mruby/mruby/issues/3013
- [x] https://github.com/mruby/mruby/issues/3014
- [x] https://github.com/mruby/mruby/issues/3015
- [x] https://github.com/mruby/mruby/issues/3016
- [x] https://github.com/mruby/mruby/issues/3017
- [x] https://github.com/mruby/mruby/issues/3018
- [x] https://github.com/mruby/mruby/issues/3019
- [x] https://github.com/mruby/mruby/issues/3020
- [x] https://github.com/mruby/mruby/issues/3021
- [x] https://github.com/mruby/mruby/issues/3022
- [x] https://github.com/mruby/mruby/issues/3023 - fixnum won't be converted to float automatically on 1.0.0.
- [x] https://github.com/mruby/mruby/issues/3024
- [x] https://github.com/mruby/mruby/issues/3025 - merged https://github.com/iij/mruby/commit/c0b5ea34a012da1ccf5466cbcdf6ad5d22e2e825
- [x] https://github.com/mruby/mruby/issues/3026 - finxum won't be converted to float automatically on 1.0.0.
- [x] https://github.com/mruby/mruby/issues/3027
- [x] https://github.com/mruby/mruby/issues/3028
- [x] https://github.com/mruby/mruby/issues/3029
- [x] https://github.com/mruby/mruby/issues/3030
- [x] https://github.com/mruby/mruby/issues/3031
- [x] https://github.com/mruby/mruby/issues/3032
- [x] https://github.com/mruby/mruby/issues/3033
- [x] https://github.com/mruby/mruby/issues/3034
- [x] https://github.com/mruby/mruby/issues/3035
- [x] https://github.com/mruby/mruby/issues/3036
- [x] https://github.com/mruby/mruby/issues/3037
- [x] https://github.com/mruby/mruby/issues/3038
- [x] https://github.com/mruby/mruby/issues/3039- merged https://github.com/iij/mruby/commit/ca723f9e9758c6cbb503d3e242d6c4c46e7e484e
- [ ] https://github.com/mruby/mruby/issues/3040 - not fixed yet
- [x] https://github.com/mruby/mruby/issues/3041
- [x] https://github.com/mruby/mruby/issues/3042

**Comment by tsahara** [comment]
出すタイミングを逸したので December に。

**Comment by tsahara** [comment]
released https://github.com/iij/mruby/releases/tag/1.0-iij20
